# Generated by Django 5.0.4 on 2024-04-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimalGameAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpiboards',
            name='ssid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rpiboards',
            name='ssid_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
