# Generated by Django 5.0.4 on 2024-04-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimalGameAPI', '0002_alter_rpiboards_ssid_alter_rpiboards_ssid_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpiboards',
            name='ssid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rpiboards',
            name='ssid_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
