# Generated by Django 5.0.4 on 2024-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimalGameAPI', '0003_alter_rpiboards_ssid_alter_rpiboards_ssid_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlogouthist',
            name='logout_hist',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
