# Generated by Django 5.0.4 on 2024-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimalGameAPI', '0004_alter_loginlogouthist_logout_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpiboards',
            name='board_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
