# Generated by Django 5.0.4 on 2024-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimalGameAPI', '0005_rpiboards_board_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstances',
            name='login_hist',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='gameinstances',
            name='logout_hist',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='LoginLogoutHist',
        ),
    ]
