# Generated by Django 5.0.4 on 2024-04-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimalGameAPI', '0006_alter_gameinstances_login_hist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpistates',
            name='start_game',
            field=models.BooleanField(default=False),
        ),
    ]
