# Generated by Django 5.0.4 on 2024-05-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimalGameAPI', '0007_rpistates_start_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpistates',
            name='gp17',
            field=models.BooleanField(default=False),
        ),
    ]
