# Generated by Django 5.0.4 on 2024-05-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimalGameAPI', '0009_rpistates_game_instance_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpistates',
            name='stop_game',
            field=models.BooleanField(default=False),
        ),
    ]
